# Generated by Django 3.2.23 on 2024-01-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AppDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo', models.URLField()),
                ('github_branch', models.URLField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='paas.app')),
            ],
        ),
        migrations.CreateModel(
            name='DatabasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField()),
                ('bandwidth', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('monthly_cost', models.FloatField()),
                ('hourly_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField()),
                ('bandwidth', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('monthly_cost', models.FloatField()),
                ('hourly_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EnvVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.URLField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='paas.appdeployment')),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Standard', 'Standard'), ('Nearline', 'Nearline'), ('Coldline', 'Coldline')], max_length=200)),
                ('database_plan', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='paas.databaseplan')),
            ],
        ),
        migrations.AddField(
            model_name='appdeployment',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='paas.database'),
        ),
        migrations.AddField(
            model_name='appdeployment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='app',
            name='deployment_plan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='paas.deploymentplan'),
        ),
        migrations.AddField(
            model_name='app',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='paas.framework'),
        ),
        migrations.AddField(
            model_name='app',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='paas.region'),
        ),
    ]
